# This is a basic workflow to help you get started with Actions

name: My workflow example

# Controls when the workflow will run
on: [workflow_dispatch]
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    explore_github_actions:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        #- uses: actions/checkout@v3
  
        # Runs a single command using the runners shell
        - name: Display username
          run: echo "GitHub Username is ${{github.actor}}"
          
        - run: echo "Repository is ${{github.repository}} and branch name is ${{github.ref}}"

        - run: echo "Event ${{github.event_name}} triggered the workflow"
        
        - name: Display runner OS
          run: echo "Runner OS is ${{runner.os}}"

        - name: Preinstalled softwares
          run: |
            echo "Display software versions"
            git -v
            docker -v
            java -version
            
        - name: Files in repository pre checkout 
          run: ls ${{github.workspace}}         

        - uses: actions/checkout@v3
        
        - name: Files in repository after checkout 
          run: ls ${{github.workspace}} 
        
